definitions:
  errorHandlers.Error:
    properties:
      details: {}
      error:
        type: string
      errorCode:
        type: string
      message:
        type: string
      statusCode:
        type: integer
    type: object
  router.emailConfirmationRequest:
    properties:
      email:
        type: string
      token:
        type: string
    type: object
  router.resetPasswordRequest:
    properties:
      email:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /send-email-confirmation:
    post:
      consumes:
      - application/json
      description: Send email confirmation mail
      parameters:
      - description: Send email confirmation object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/router.emailConfirmationRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/errorHandlers.Error'
        "500":
          description: Internal server error if server fails
          schema:
            $ref: '#/definitions/errorHandlers.Error'
      summary: Send email confirmation mail
  /send-reset-password:
    post:
      consumes:
      - application/json
      description: Send reset password mail
      parameters:
      - description: Send reset password object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/router.resetPasswordRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/errorHandlers.Error'
        "500":
          description: Internal server error if server fails
          schema:
            $ref: '#/definitions/errorHandlers.Error'
      summary: Send reset password mail
swagger: "2.0"