FROM rust:1.88.0 AS builder

ARG APP_NAME

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY apps/backend/ ./apps/backend/
COPY libs/ ./libs/

ENV APP_NAME=${APP_NAME}

RUN cargo build -p ${APP_NAME}

FROM rust:1.88.0 as runner

ARG APP_NAME

WORKDIR /app

COPY --from=builder /app/target/debug/ ./

COPY migrations/ ./migrations/

ENV MIGRATIONS_DIR=/app/migrations

RUN echo "#!/bin/sh\n./${APP_NAME}" > entrypoint.sh

RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]
