definitions:
  errorHandlers.Error:
    properties:
      details: {}
      error:
        type: string
      errorCode:
        type: string
      message:
        type: string
      statusCode:
        type: integer
    type: object
  router.uploadResponse:
    properties:
      link:
        type: string
    type: object
info:
  contact: {}
paths:
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload file
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      - description: Folder
        in: formData
        name: folder
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: File path
          schema:
            $ref: '#/definitions/router.uploadResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/errorHandlers.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/errorHandlers.Error'
      summary: Upload file
      tags:
      - Files
swagger: "2.0"