# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json

version: 1

metadata:
    name: Task Manager Setup App, Provider, Flow, Stages

entries:
    # GROUPS

    - model: authentik_core.group
      id: task-manager-group
      identifiers:
          name: Task Manager
      attrs:
          name: Task Manager

    # COMMON POLICIES

    - model: authentik_policies_expression.expressionpolicy
      id: check-if-email-unique
      identifiers:
          name: check-if-email-unique
      attrs:
          name: check-if-email-unique
          expression: |
              from authentik.core.models import User
              from django.core.exceptions import ValidationError

              email = context.get('prompt_data', {}).get('email')

              if not email:
                  return True

              existing_users = User.objects.filter(email__iexact=email)

              if request.user.is_authenticated:
                  existing_users = existing_users.exclude(pk=request.user.pk)

              if existing_users.exists():
                  raise ValidationError("User with this email already exists.")

              return True

    # SIGN UP FLOW
    # FLOW

    - model: authentik_flows.flow
      id: task-manager-sign-up-flow
      identifiers:
          slug: task-manager-sign-up-flow
          name: task-manager-sign-up-flow
      attrs:
          slug: task-manager-sign-up-flow
          name: task-manager-sign-up-flow
          designation: enrollment
          compatibility_mode: true
          title: Sign Up

    # STAGES

    - model: authentik_stages_prompt.promptstage
      id: task-manager-sign-up-flow-prompt-stage
      identifiers:
          name: task-manager-sign-up-flow-prompt-stage
      attrs:
          name: task-manager-sign-up-flow-prompt-stage
          validation_policies:
              - !KeyOf check-if-email-unique
          fields:
              - !Find [
                    authentik_stages_prompt.prompt,
                    [name, default-source-enrollment-field-username]
                ]
              - !Find [authentik_stages_prompt.prompt, [name, initial-setup-field-email]]
              - !Find [authentik_stages_prompt.prompt, [name, initial-setup-field-password]]
              - !Find [authentik_stages_prompt.prompt, [name, initial-setup-field-password-repeat]]

    - model: authentik_stages_user_write.userwritestage
      id: task-manager-sign-up-flow-user-write-stage
      identifiers:
          name: task-manager-sign-up-flow-user-write-stage
      attrs:
          name: task-manager-sign-up-flow-user-write-stage
          user_type: internal
          create_users_group: !KeyOf task-manager-group
          create_users_as_inactive: false

    # STAGE -> FLOW BINDINGS

    - model: authentik_flows.flowstagebinding
      id: task-manager-sign-up-flow-prompt-stage-binding
      identifiers:
          target: !KeyOf task-manager-sign-up-flow
          stage: !KeyOf task-manager-sign-up-flow-prompt-stage
      attrs:
          target: !KeyOf task-manager-sign-up-flow
          stage: !KeyOf task-manager-sign-up-flow-prompt-stage
          policy_engine_mode: any
          order: 10

    - model: authentik_flows.flowstagebinding
      id: task-manager-sign-up-flow-user-write-stage-binding
      identifiers:
          target: !KeyOf task-manager-sign-up-flow
          stage: !KeyOf task-manager-sign-up-flow-user-write-stage
      attrs:
          target: !KeyOf task-manager-sign-up-flow
          stage: !KeyOf task-manager-sign-up-flow-user-write-stage
          policy_engine_mode: any
          order: 20
          policy: []

    - model: authentik_flows.flowstagebinding
      id: task-manager-sign-up-flow-user-login-stage-binding
      identifiers:
          target: !KeyOf task-manager-sign-up-flow
          stage:
              !Find [
                  authentik_stages_user_login.userloginstage,
                  [name, default-authentication-login]
              ]
      attrs:
          target: !KeyOf task-manager-sign-up-flow
          stage:
              !Find [
                  authentik_stages_user_login.userloginstage,
                  [name, default-authentication-login]
              ]
          policy: []
          order: 100
          re_evaluate_policies: true

    # POLICY -> STAGE BINGING

    # - model: authentik_policies.policybinding
    #   identifiers:
    #     policy: !KeyOf check-if-email-unique
    #     target: !KeyOf task-manager-sign-up-flow-user-write-stage-binding
    #   attrs:
    #     policy: !KeyOf check-if-email-unique
    #     target: !KeyOf task-manager-sign-up-flow-user-write-stage-binding
    #     order: 0
    #     enabled: true
    #     failure_result: false

    # AUTH FLOW COMBINED
    # FLOW

    - model: authentik_flows.flow
      id: auth-flow-combined
      identifiers:
          name: Auth Flow Combined
          slug: auth-flow-combined
      attrs:
          slug: auth-flow-combined
          name: Auth Flow Combined
          title: Login
          designation: authentication
          compatibility_mode: true

    # STAGES

    - model: authentik_stages_identification.identificationstage
      id: auth-flow-combined-identification-stage
      identifiers:
          name: auth-flow-combined-identification-stage
      attrs:
          name: auth-flow-combined-identification-stage
          enable_remember_me: true
          password_stage:
              !Find [
                  authentik_stages_password.passwordstage,
                  [name, default-authentication-password]
              ]
          enrollment_flow: !KeyOf task-manager-sign-up-flow
          user_fields:
              - email
              - username
          case_insensitive_matching: true
          show_matched_user: false
          pretend_user_exists: false

    # STAGE -> FLOW BINGINGS

    - model: authentik_flows.flowstagebinding
      id: auth-flow-combined-identification-stage-binding
      identifiers:
          target: !KeyOf auth-flow-combined
          stage: !KeyOf auth-flow-combined-identification-stage
      attrs:
          target: !KeyOf auth-flow-combined
          stage: !KeyOf auth-flow-combined-identification-stage
          policy_engine_mode: any
          order: 10
          re_evaluate_policies: true

    - model: authentik_flows.flowstagebinding
      id: auth-flow-combined-authenticator-validation-stage-binding
      identifiers:
          target: !KeyOf auth-flow-combined
          stage:
              !Find [
                  authentik_stages_authenticator_validate.authenticatorvalidatestage,
                  [name, default-authentication-mfa-validation]
              ]
      attrs:
          target: !KeyOf auth-flow-combined
          stage:
              !Find [
                  authentik_stages_authenticator_validate.authenticatorvalidatestage,
                  [name, default-authentication-mfa-validation]
              ]
          order: 20
          policy: []

    - model: authentik_flows.flowstagebinding
      id: auth-flow-combined-user-login-stage-binding
      identifiers:
          target: !KeyOf auth-flow-combined
          stage:
              !Find [
                  authentik_stages_user_login.userloginstage,
                  [name, default-authentication-login]
              ]
      attrs:
          target: !KeyOf auth-flow-combined
          stage:
              !Find [
                  authentik_stages_user_login.userloginstage,
                  [name, default-authentication-login]
              ]
          policy: []
          order: 100
          re_evaluate_policies: true

    # POLICY -> STAGE BINGINGS

    - model: authentik_policies.policybinding
      id: auth-flow-combined-user-login-stage-binding-flow-password-policy
      identifiers:
          target: !KeyOf auth-flow-combined-identification-stage-binding
          policy:
              !Find [
                  authentik_policies_expression.expressionpolicy,
                  [name, default-authentication-flow-password-stage]
              ]
      attrs:
          target: !KeyOf auth-flow-combined-identification-stage-binding
          policy:
              !Find [
                  authentik_policies_expression.expressionpolicy,
                  [name, default-authentication-flow-password-stage]
              ]
          enabled: true
          failure_result: true
          order: 10
          negate: false
          timeout: 30
          re_evaluate_policies: true

    # PROVIDERS

    - model: authentik_providers_oauth2.oauth2provider
      id: task-manager-provider
      identifiers:
          name: Task Manager Provider
      attrs:
          name: Task Manager Provider
          client_id: !Env "AUTHENTIK_CLIENT_ID"
          client_type: public
          authentication_flow: !KeyOf auth-flow-combined
          access_token_validity: minutes=15
          sub_mode: user_uuid
          signing_key:
              !Find [
                  authentik_crypto.certificatekeypair,
                  [name, "authentik Self-signed Certificate"]
              ]
          redirect_uris:
              - matching_mode: strict
                url: !Env "AUTHENTIK_REDIRECT_URI"
              - matching_mode: strict
                url: !Env "AUTHENTIK_REDIRECT_URI_SILENT"
          authorization_flow:
              !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow:
              !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          property_mappings:
              - !Find [
                    authentik_providers_oauth2.scopemapping,
                    [name, "authentik default OAuth Mapping: OpenID 'email'"]
                ]
              - !Find [
                    authentik_providers_oauth2.scopemapping,
                    [name, "authentik default OAuth Mapping: OpenID 'openid'"]
                ]
              - !Find [
                    authentik_providers_oauth2.scopemapping,
                    [name, "authentik default OAuth Mapping: OpenID 'profile'"]
                ]

    # APPLICATIONS

    - model: authentik_core.application
      id: task-manager-app
      identifiers:
          slug: !Env "AUTHENTIK_SLUG"
      attrs:
          name: "Task Manager"
          slug: !Env "AUTHENTIK_SLUG"
          provider: !KeyOf task-manager-provider
          policy_engine_mode: any

